version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGGO_URI: mongodb://mongo:27017/test
      PORT: 8000
    depends_on:
      - mongo
    restart: always
    networks:
      - my_network
    command: ["bash", "-c", "sleep 10 && npm run seed && node dist"]
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
